owner: meermubashar
repo: upptime
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

sites:
  - name: Meer Mubashar (Homepage)
    url: https://meermubashar.com
  - name: Meer Mubashar (Server Health)
    url: https://meermubashar.com/healthcheck.php
  - name: Suii Dhaaga Clothing
    url: https://suiidhaagaclothing.com
  - name: The Media Lenses
    url: https://themedialenses.com

assignees:
  - meermubashar

status-website:
  cname: status.meermubashar.com
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Meer Mubashar Status
  introTitle: "**Meer Mubashar Status** monitors uptime for all my key sites."
  introMessage: >
    This status page shows live availability and historical
    performance data for my sites. It is powered entirely by
    GitHub Actions, Issues, and Pages using Upptime.
  navbar:
    - title: Status
      href: /
    - title: Main Website
      href: https://meermubashar.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: >
    Powered by [Upptime](https://upptime.js.org) and maintained by [Meer Mubashar](https://meermubashar.com).
